version: "3"
services:
  db_blockchain:
    image: postgres
    environment:
      - POSTGRES_USER=root_blockchain
      - POSTGRES_PASSWORD=root_blockchain
      - POSTGRES_DB=postgres_blockchain
    ports:
      - "5433:5432"
    volumes:
      - pgdata_blockchain:/var/lib/postgresql/data
volumes:
  pgdata_blockchain:
